runtime: go111

handlers:
- url: /api/.*
  script: auto
  secure: always
- url: /ext/.*
  script: auto
  secure: always
  login: admin
- url: /
  static_files: static/index.html
  upload: static/index\.html
  secure: always
  http_headers:
    Strict-Transport-Security: max-age=31536000; includeSubDomains
    X-Frame-Options: DENY
- url: /(.+)\.(txt|css|js|ico|png|svg|jpg|eot|ttf|woff|woff2)
  static_files: static/\1.\2
  upload: static/(.+)
  secure: always
